include:
  - ./src/Deploy/RabbitMQ/docker-compose.yml
  - ./src/Deploy/SQL/docker-compose.yml

  - ./src/Services/UserService/docker-compose.yml
  - ./src/Services/BookingService/docker-compose.yml
  - ./src/Services/FinanceService/docker-compose.yml

networks:
  microservices-network:
    external: true